import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Pixarzo | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-JakartaFont">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
